### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by tanaka-de-silva** [zilverline/event-sourced-blog-example#1]
Thanks for creating this sample and the associated blog posts, they have been very helpful to get an idea of how to use ES in a "real world" setting. I really like to use this architecture and would like to bootstrap a pet project with some of the Scala code in this repository and would like to know if this is possible and know if there are any license conditions outside of attribution if it is possible to do so.

**Comment by erikrozendaal** [comment]
Hi Tanaka, 

You're free to use this code any way you want, no warranty though :)

Erik
